plugins {
    id "com.android.application"
}

android {
    namespace "com.zip2jar"
    compileSdk 34

    defaultConfig {
        applicationId "com.zip2jar"
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main { assets.srcDirs = ["../../zip2jar"] }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
